package com.willay.audit;

/** Catálogo de acciones auditables. Se amplía por etapa. */
public enum AccionAuditoria {
    LOGIN_OK, LOGIN_FALLIDO, LOGOUT,
    CUENTA_ACTIVADA, ACTIVACION_FALLIDA,
    TOKEN_REFRESCADO, PASSWORD_CAMBIADA, PASSWORD_RECUPERADA,
    ACCESO_BLOQUEADO_POR_INTENTOS,
    ALUMNO_CREADO, ALUMNO_ACTUALIZADO, ALUMNO_RETIRADO, TARJETA_VINCULADA, CUENTA_ALUMNO_CREADA,
    DOCENTE_CREADO, DOCENTE_ACTUALIZADO, DOCENTE_CESADO,
    CUENTA_APODERADO_CREADA, APODERADO_ELIMINADO,
    AULA_CREADA, AULA_ACTUALIZADA, AULA_DESACTIVADA,
    MATRICULA_REGISTRADA, IMPORTACION_MASIVA,
    COLEGIO_CREADO, COLEGIO_ESTADO_CAMBIADO, COLEGIO_PAGO_ACTUALIZADO,
    COMUNICADO_GLOBAL_ENVIADO
}
