package com.willay.audit;

/** Catálogo de acciones auditables. Se amplía por etapa. */
public enum AccionAuditoria {
    LOGIN_OK, LOGIN_FALLIDO, LOGOUT,
    CUENTA_ACTIVADA, ACTIVACION_FALLIDA,
    TOKEN_REFRESCADO, PASSWORD_CAMBIADA,
    ACCESO_BLOQUEADO_POR_INTENTOS,
    ALUMNO_CREADO, ALUMNO_ACTUALIZADO, ALUMNO_RETIRADO,
    DOCENTE_CREADO, DOCENTE_ACTUALIZADO, DOCENTE_CESADO,
    AULA_CREADA, AULA_ACTUALIZADA, AULA_DESACTIVADA,
    MATRICULA_REGISTRADA, IMPORTACION_MASIVA,
    COLEGIO_CREADO, COLEGIO_ESTADO_CAMBIADO
}
